### ISSUE TITLE
How do I import the data?

### ISSUE THREAD

**Issue by ene1801** [ene1801/effective-adventure#1]
### HERE WE ARE...
Figure out what you minimally need to know in order to complete your assignment. @ene1801

`help.txt` is a good place to start. Here is some emoji. ⚽

**Comment by ene1801** [comment]
This should resolve issue #1

**Comment by ene1801** [comment]
👍

**Comment by studencio** [comment]
It's good that you closed this issue, but there is something else that is bothering me. What do you intend to do about the assignment?
